CC=gcc
EXCFLAGS=-ec-prefix c/
CFLAGS=-O0 -g -fPIC -Wall -Werror -ansi -pedantic -I. \
 -Wno-unused-function
LIBS=-ldl
SHARED=-shared

# FIXME: These are GNU make specific :(
CSRC=$(addprefix c/,$(SRC:.exc=.c))
OBJS=$(addprefix o/,$(SRC:.exc=.o))

csrc: $(CSRC)

c/exists:
	mkdir -p c
	touch c/exists

c/%.c: %.exc c/exists
	-$(EXC) $(EXCFLAGS) $(CFLAGS) -eonly $<

o/exists:
	mkdir -p o
	touch o/exists

o/%.o: c/%.c o/exists $(CSRC)
	$(CC) $(CFLAGS) -c $< -o $@
